title: Abe Barranca # your name (or website title) here
logo: "/images/Barranca-headshot.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome! This is a repository for my data science projects. I am a data enthusiast trained in social science methods.
  <br><br>
  I'm passionate about data-driven decision making in business and government and am an NBA basketball enthusiast. 
  <br><br>
  <a href="https://www.linkedin.com/in/abe-barranca-380b1725/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
